api : 
    build : ./api
    ports : 
        - 3000 : 3000
    volumes : 
        - ./api:/go/src/github.com/mk0812/vue-golang-stockprice/api
    links : 
        - database
    environment : 
        - DB_NAME = {vue-golang-stockprice}

database:  
    image: mongo:3.0
    command: mongod --smallfiles --quiet --logpath=/dev/null